### ISSUE TITLE
Consider using ansigenome.

### ISSUE THREAD

**Issue by ypid** [weareinteractive/ansible-cron#3]
To avoid errors like these: https://github.com/weareinteractive/ansible-cron/blame/4c13faba1b88fe001a266519601f3555c809fdbc/README.md#L25

**Comment by ypid** [comment]
Also Ansible Galaxy badge is wrong.

**Comment by franklinkim** [comment]
will take a loot at it and thx for the hint, I fixed the c&p erros

**Comment by ypid** [comment]
What do you thing about ansigenome? Not worth using?

**Comment by franklinkim** [comment]
No, definitely a great tool! I tested it and I can easily reproduce my README files. 

Unfortunately it's only on a multiple role basis. Since I manage multiple roles from multiple clients and sources I would need it to be on a per role basis. Thus also ensuring that if someone else forks my role he can generate the same README file. 

It might be sth worth to propose as a feature and I'll look into it again when I have more time for it.

**Comment by ypid** [comment]
> Thus also ensuring that if someone else forks my role he can generate the same README file.

Thats also something I encountered …

All right. Check it out, when you have time :+1:

**Comment by franklinkim** [comment]
So here's my first try in resolving this issue: [ansible-role gem](https://rubygems.org/gems/ansible-role)

I admit , it's an early alpha version and currently pretty much tailored to my needs, but it might be a starting point. 

you can see my first role [here](https://github.com/weareinteractive/ansible-apache2)

**Comment by ypid** [comment]
Interesting, you like Ruby I guess …

**Comment by franklinkim** [comment]
haven't done too much ruby lately so I'm giving it a try again :)
